version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: fm-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200M'
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: fm-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REQUEST_TIMEOUT_MS: 2000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '400M'
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    container_name: fm-kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - LOGGING_LEVEL_COM_PROVECTUS=warn
      - LOGGING_LEVEL_ROOT=warn
    links:
      - kafka
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '400M'
  postgres:
    image: postgres:15.4-alpine
    container_name: fm-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fmdb
      - POSTGRES_USER=fmuser
      - POSTGRES_PASSWORD=fmpass
    volumes:
      - fmdb-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '100M'
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: fm-elk
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=fmpass
      - xpack.security.enabled=false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'
  logstash:
    image: logstash:8.11.0
    container_name: fm-logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      - ELASTIC_PASSWORD=fmpass
    volumes:
      - fm-logstash-data:/var/lib/logstash/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'
  kibana:
    image: kibana:8.11.0
    container_name: fm-kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'

volumes:
  fmdb-data:
    driver: local
    name: "fmdb-data-volume"
  fm-logstash-data:
    driver: local
    name: "fm-logstash-data-volume"