name: Java CI with Gradle

on:
  push:
    branches: [ "main", "feature/github-actions-test" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          gradle-version: current
          arguments: build jacocoTestReport
      - name: Add coverage
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/all/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code coverage
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
